#ifndef SD2PSXMAN_RPC_COMMONDEF
#define SD2PSXMAN_RPC_COMMONDEF

#define SD2PSXMAN_IRX 0xB0355

enum PS2IPS_RPC_ID {
    SD2PSX_QUIT_BOOTCARD = 1,
    SD2PSX_SWITCH_CARD_SLOT,
    SD2PSX_SWITCH_CARD_CHANNEL,
    SD2PSX_SWITCH_CARD_SLOT_BY_GAMEID,
    SD2PSX_SEND_CMD,
    SD2PSX_CMD_COUNT
};
#endif